#!/bin/sh

csvgrep -c Text -r '(?mx)  # Match ^ on each line. ("." does not match "\n".)
            ^(`{3,})(?!`)(?!.*\1)  # A code fence, not all one one line.
            [a-z]*                 # Optional lowercase.
            (?:[^a-z\s]            # Non-whitespace non-lowercase.
              |[ \t]+\S)           # Or blanks followed by non-whitespace.
        ' fences.csv |
    csvcut -c 'Post Link' |
    grep -oP '""id"": \K\d+' |
    xargs printf 'https://askubuntu.com/posts/%s/revisions\n'
