#!/bin/sh
# filter-fences - Uses csvgrep to find posts that may have broken code fences.

# shellcheck disable=SC2016  # The operand to csvgrep -r is meant literally.

csvgrep -c Text -r '(?mx)  # Match ^ on each line. ("." does not match "\n".)
            ^[ \t]*(`{3,})(?!`)(?!.*\1)  # A code fence, not all one one line.
            [a-z]*                       # Optional lowercase.
            (?:[^a-z\s]                  # Non-whitespace non-lowercase, OR
              |[ \t]+\S)                 #   blanks followed by non-whitespace.
        ' fences.csv |
    csvcut -c 'Post Link' |
    sed 1d |  # Remove header line (that says "Post Link").
    xargs printf 'https://askubuntu.com/posts/%s/revisions\n'
